/*
 *     Copyright (C) 2024 Valeri Gokadze
 *
 *     Musify is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     Musify is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 *
 *     For more information about Musify, including how to contribute,
 *     please visit: https://github.com/gokadzev/Musify
 */

List albumsDB = [
  {
    'ytid': 'PLS5_MK8e_MzSNmCQ3_AqbQL1JOM4Yy-_v',
    'title': 'Starboy - The Weeknd',
    'image': 'https://i.scdn.co/image/ab67616d0000b2734718e2b124f79258be7bc452',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLtdokPm7vPss1TXrV4gr2pnSXmMu-UFF4',
    'title': 'Dawn FM - The Weeknd',
    'image': 'https://i.scdn.co/image/ab67616d0000b2734ab2520c2c77a1d66b9ee21d',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLOkPWZS9Q7ECOreiaeGJZ_dA8KlCtsvHN',
    'title': 'AM - Arctic Monkeys',
    'image': 'https://i.scdn.co/image/ab67616d0000b2734ae1c4c5c45aabe565499163',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL9tY0BWXOZFuFZ-n1neSQ9R619SDUDSyl',
    'title': 'Lover - Taylor Swift',
    'image': 'https://i.scdn.co/image/ab67616d0000b273d64d9e6e9b7897ead3279cff',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLfSdF_HSSu55q-5p-maISZyr19erpZsTo',
    'title': "Harry's House - Harry Styles",
    'image': 'https://i.scdn.co/image/ab67616d0000b2732e8ed79e177ff6011076f5f0',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLfSdF_HSSu548MHnItRg7sYbj1OkmFc2g',
    'title': 'Fine Line - Harry Styles',
    'image': 'https://i.scdn.co/image/ab67616d0000b27377fdcfda6535601aff081b6a',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLK2zhq9oy0K4yxwMmBPsXQ3NvaQSxw6rY',
    'title': 'My Dear Melancholy - The Weeknd',
    'image': 'https://i.scdn.co/image/ab67616d0000b2731f6a2a40bb692936879db730',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLsCPTY_MPoPZLKsjasPhYLuoWG-s-rdKq',
    'title': 'Happier Than Ever - Billie Eilish',
    'image': 'https://i.scdn.co/image/ab67616d0000b2732a038d3bf875d23e4aeaa84e',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLHwvDXmNUa93H0TFpFvKK1wD3WupLzcHd',
    'title': 'SOUR - Olivia Rodrigo',
    'image': 'https://i.scdn.co/image/ab67616d0000b273a91c10fe9472d9bd89802e5a',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL2YYYbxwOUaKedFVO8nv_HY_0XZCH00S4',
    'title': 'Beauty Behind The Madness - The Weeknd',
    'image': 'https://i.scdn.co/image/ab67616d0000b2737fcead687e99583072cc217b',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL2YYYbxwOUaIUIjvLgpVyn_K4-IIl3mFc',
    'title': 'After Hours - The Weeknd',
    'image': 'https://i.scdn.co/image/ab67616d0000b2738863bc11d2aa12b54f5aeb36',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLorwKgiUml5v7dtrSLgvs6p-Y3oCh61yU',
    'title': "Don't Smile at Me - Billie Eilish",
    'image': 'https://i.scdn.co/image/ab67616d00001e02a9f6c04ba168640b48aa5795',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLmU8B4gZ41icgJv5WmjkK6c3KyOpVEDkI',
    'title': "1989 (Taylor's Version) - Taylor Swift",
    'image': 'https://i.scdn.co/image/ab67616d0000b273904445d70d04eb24d6bb79ac',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL7V-LJGDr4W8z5XbbROMq19AWCyyh-lF4',
    'title': 'Born To Die - Lana Del Rey',
    'image': 'https://i.scdn.co/image/ab67616d0000b273cb76604d9c5963544cf5be64',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLu8BgVaWowIFIoeD8JZTuHZRGt5KcDmxR',
    'title': 'Cry Baby - Melanie Martinez',
    'image': 'https://i.scdn.co/image/ab67616d0000b273fba13f993c51c1985756c668',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLnBDayR0gzwyD-F1nBgx3Gt4wO9h8pJSB',
    'title': 'Night Visions - Imagine Dragons',
    'image': 'https://i.scdn.co/image/ab67616d0000b273a8f95e7f840c11edfa6cc3bd',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLE3uncMq8x3wLUlOD9W0c8-A8ZIZHUj6L',
    'title': 'Wasteland - Brent Faiyaz',
    'image': 'https://i.scdn.co/image/ab67616d0000b27369f63a842ea91ca7c522593a',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL2BpnHM2wLCtglIEFILC9Z1jz7LdUOneO',
    'title': "Emails I can't send - Sabrina Carpenter",
    'image': 'https://i.scdn.co/image/ab67616d0000b273700f7bf79c9f063ad0362bdf',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL1z9R7TJXY8wQT8P-jsjgdRFvjkte_Akn',
    'title': 'Planet Her - Doja Cat',
    'image': 'https://i.scdn.co/image/ab67616d0000b273be841ba4bc24340152e3a79a',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLWrMgSHVv2bPQUSEZnrep56vxWVech7gT',
    'title': 'SOS - SZA',
    'image': 'https://i.scdn.co/image/ab67616d0000b27370dbc9f47669d120ad874ec1',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL9tY0BWXOZFsRO7M8bLf-PKpUfFP48Jha',
    'title': 'HEROES & VILLAINS - Metro Boomin',
    'image': 'https://i.scdn.co/image/ab67616d0000b273c4fee55d7b51479627c31f89',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLfiMjLyNWxeYae8z1QiwSLTK12G_6EQU_',
    'title': 'Surface Sounds - KALEO',
    'image': 'https://i.scdn.co/image/ab67616d0000b2735956beefe0c79f85aec384b6',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lYFD0sDFxZ8cr9ttczB7pH1zYc8r16kkg',
    'title': 'GOLDEN - Jung Kook',
    'image': 'https://i.scdn.co/image/ab67616d0000b273741fd4807f442af3f7359316',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLWOP54w8bbgM2Qlyks0Bt6GQOODjjfJY-',
    'title': 'Christmas - Michael Bublé',
    'image': 'https://i.scdn.co/image/ab67616d0000b27395517befb15ad5d63af701ab',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lw2-Cu3aRY2Tkfi28_79m05SkBF_tlufg',
    'title': 'Midnights - Taylor Swift',
    'image': 'https://i.scdn.co/image/ab67616d0000b273bb54dde68cd23e2a268ae0f5',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mFp59TqeoWXnMKVRThBlLdVyVXz0pjaYk',
    'title': 'Merry Christmas - Mariah Carey',
    'image': 'https://i.scdn.co/image/ab67616d0000b2734246e3158421f5abb75abc4f',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lb5kz8gsKmocY458o2B5FUAtmuG3sNcH4',
    'title': 'Scarlet - Doja Cat',
    'image': 'https://i.scdn.co/image/ab67616d0000b27394203dd82d27b494c777d07c',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_n6zWDEznvX5Lz6Q8SMCeiEcJk87sKh0XI',
    'title': 'Ferxxocalipsis - Feid',
    'image': 'https://i.scdn.co/image/ab67616d0000b273f1aad814a40ec7419c234242',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLbxg9IbgCVkThXxuKK8bkMw3WUt5gqrts',
    'title': 'Everyday Is Christmas - Sia',
    'image': 'https://i.scdn.co/image/ab67616d0000b273d1410c1372fab1e516328fa8',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mUTfdj6ahy1pcLm_ocVbcWXrhB99Q0KmU',
    'title': 'Thank u,next - Ariana Grande',
    'image': 'https://i.scdn.co/image/ab67616d0000b27356ac7b86e090f307e218e9c8',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lnx0vO7zWw_AcGVVHsaDvsowsRQiIjBMk',
    'title': 'Evolve - Imagine Dragons',
    'image': 'https://i.scdn.co/image/ab67616d0000b2735675e83f707f1d7271e5cf8a',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_l38zxOdBaYnNtz_thk94HRP8V5s6_oGsU',
    'title': 'This Is Acting - Sia',
    'image': 'https://i.scdn.co/image/ab67616d0000b27349e0134c686547c28b7c999f',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nRIwFxK9HoO5lNT4THuPKYfit57ZgBxdM',
    'title': 'What Is Love? - Clean Bandit',
    'image': 'https://i.scdn.co/image/ab67616d0000b27337fb0680110fbb107740de5d',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lTUCPSiT_kZOCY1BlJ1t5T5nsxeG6v20s',
    'title': 'DRIVE - Tiësto',
    'image': 'https://i.scdn.co/image/ab67616d0000b27375544696cbe0e019eaf0fcbb',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nF3Y8B3Dljpk27p5o0adXl0jQJXR_pVj8',
    'title': 'Don Juan - Maluma',
    'image': 'https://i.scdn.co/image/ab67616d0000b273d688b951a19f48941682e026',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nRTHZ_yD4II6q7KlgQo1Fd6I05cPyThs8',
    'title': 'THINK LATER - Tate McRae',
    'image': 'https://i.scdn.co/image/ab67616d0000b27377eb7a5b9367de79c3b92a49',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nxmoDMMD7YOXBekv9Pt-55UoMI0tKDlyU',
    'title': 'Scorpion - Drake',
    'image': 'https://i.scdn.co/image/ab67616d0000b273f907de96b9a4fbc04accc0d5',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mC1dIZC9-5x3XR2TJP-KpxiVaA_L_U9K8',
    'title': 'LOOK AT ME - XXXTENTACION',
    'image': 'https://i.scdn.co/image/ab67616d0000b27352cc5e3765a135c52e1bbbbc',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_m5riLsB5iVpADmWfHmzkFNc8QGBWwBkWM',
    'title': 'SKINS - XXXTENTACION',
    'image': 'https://i.scdn.co/image/ab67616d0000b273da9e59639a9759d8952890c6',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lqRFvHXwqV_C6J-_ruobnyZgR2K6Ql8Qk',
    'title': '? - XXXTENTACION',
    'image': 'https://i.scdn.co/image/ab67616d0000b273806c160566580d6335d1f16c',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lkSMrwgF3m0BCgIA0v1G1VZhSscZg37cY',
    'title': 'The Show - Niall Horan',
    'image': 'https://i.scdn.co/image/ab67616d0000b2732a368fea49f5c489a9dc3949',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kq_gJdWJ9LUwgYzXMWeocvSyee4OqsvOQ',
    'title': 'Norman Fucking Rockwell! - Lana Del Rey',
    'image': 'https://i.scdn.co/image/ab67616d0000b273879e9318cb9f4e05ee552ac9',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lFbfW_UOra8dYRTa69lxR3fxYjogNtiQw',
    'title': 'THE TORTURED POETS DEPARTMENT - Taylor Swift',
    'image': 'https://i.scdn.co/image/ab67616d0000b2735076e4160d018e378f488c33',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lVxq_QCXDlleCnpsszQyiFextilkX12_w',
    'title': "WE DON'T TRUST YOU - Future, Metro Boomin",
    'image': 'https://i.scdn.co/image/ab67616d00001e02a46b07c291e6dfdee13b3ee8',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kZqVnh5DXwZ95R5yuAnWUX20OjrNJh09U',
    'title': 'Fireworks & Rollerblades - Benson Boone',
    'image': 'https://i.scdn.co/image/ab67616d0000b273cc04ff3e70e146ba9abacf40',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mbcpEgHbfi3deQRnyGfQWnlzgQd86_tMI',
    'title': 'Wasteland, Baby! - Hozier',
    'image': 'https://i.scdn.co/image/ab67616d00001e025795e01c151ba5a8ce4bd295',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mG42_gxfZ-Cq6Y921XWm43Z75YAiaSIWI',
    'title': 'eternal sunshine (slightly deluxe) - Ariana Grande',
    'image': 'https://i.scdn.co/image/ab67616d0000b273bd3de668e4784d791c4ab695',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kmtA2RV4sA_baCJwuaazeDtKmBM85j-yo',
    'title': 'UTOPIA - Travis Scott',
    'image': 'https://i.scdn.co/image/ab67616d00001e02881d8d8378cd01099babcd44',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kDuqdPyyBdToRV-mvWklRE_ysv7-LqveI',
    'title': 'One Thing At A Time - Morgan Wallen',
    'image': 'https://i.scdn.co/image/ab67616d0000b273705079df9a25a28b452c1fc9',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kFa9tOyLsP4JH1EqSD3hIudVdkmQWfKT0',
    'title': 'DECIDE - Djo',
    'image': 'https://i.scdn.co/image/ab67616d0000b273fddfffec51b4580acae727c1',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_ngyCd9rAr-KZ5eI5juhaOe-LgrjlteONU',
    'title':
        'Hard To Imagine The Neighbourhood Ever Changing - The Neighbourhood',
    'image': 'https://i.scdn.co/image/ab67616d0000b2739b6ac98a52f62d5cb473da40',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLsCPTY_MPoPbEMmr8uZ7msRYcYtDz0g9g',
    'title': 'HIT ME HARD AND SOFT - Billie Eilish',
    'image': 'https://i.scdn.co/image/ab67616d0000b27371d62ea7ea8a5be92d3c1f62',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_m2MkFaiKAqsvU8RR3o1qAGMLkSCtIl8vU',
    'title': '12 Notes - Alec Benjamin',
    'image': 'https://i.scdn.co/image/ab67616d0000b27310937fa41a9718c72a59d85b',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nH6vZsFvVyJt06PcH5O9SXqV5lT3-I5hY',
    'title': 'Narrated For You - Alec Benjamin',
    'image': 'https://i.scdn.co/image/ab67616d0000b273459d675aa0b6f3b211357370',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kClWWfWghQXro7ONQ-DfH3RZ1oxiu0kMA',
    'title': 'Blonde - Frank Ocean',
    'image': 'https://i.scdn.co/image/ab67616d0000b273c5649add07ed3720be9d5526',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lhps_W4LDJGQ--XKY8-4s1-DT98XKn7PI',
    'title': 'Cigarettes After Sex - Cigarettes After Sex',
    'image': 'https://i.scdn.co/image/ab67616d0000b273ced182a9a86195e9ba2a5183',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_m4lOn8HJoLfTETxg2d6QouxcQd3nM4Gf0',
    'title': 'Parachutes - Coldplay',
    'image': 'https://i.scdn.co/image/ab67616d0000b2739164bafe9aaa168d93f4816a',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mI1LaRKdjRV-QCXbqdSLwRgG7vHthQgnQ',
    'title': 'Ariana Grande - Positions',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nRIwFxK9HoO5lNT4THuPKYfit57ZgBxdM',
    'title': 'Clean Bandit - What Is Love?',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_k4LFwctseSNnXT0MyeNB1j9boPLFjO-ZI',
    'title': 'One Direction - Four',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mJzZNV67c56hX-m1jSQ9wQImckazmxN5s',
    'title': 'Melanie Martinez - Cry Baby',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kTAMVwktrxHt4YYl0HVqtInDsZZu-842I',
    'title': 'Camila Cabello - Romance',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kgvDzTzHW2NHKXbZ6kzcoCY-XfVE0c-Sc',
    'title': 'Luis Fonsi - Vida',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_k-LckFrVH6iHyG_RDQCBDQ-k9rJNnZ85c',
    'title': 'Rauw Alejandro - Vice Versa',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_m6Sss1kO7j8so_ce3sDT8Xa5RZz6mERNQ',
    'title': 'Drake - Take Care',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nUljIDktkB7qCIEoc-vn1J26T-nHtC1cM',
    'title': 'Peso Pluma - Genesis',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kng4OEgFEJ1lxWRj7wjxewLbSAu6vmzzE',
    'title': 'One Direction - Made In The A.M.',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kBgKPNpRX_z9Ecob9x9Q7qaEMCc5wvCvI',
    'title': 'Imagine Dragons - Mercury - Act 1 / 2',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_keyJA-JsoAdfCylvyyIQMRjenzX6MzmnE',
    'title': 'Kanye West - The Life Of Pablo',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nQNRQA99R_mdFaftHhYqCHyNLgWjUhHZ0',
    'title': 'Karol G - Kg0516',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_m-vSVOiVeY_z2lPgThmS6Nn0TJExXZtOg',
    'title': 'Taylor Swift - Evermore',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lHYbVGaxOAVNP1tAgVKXBAxnIJ-OqbfLQ',
    'title': 'Jonas Blue - Blue',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nbgX8HX7Q8nc2RBTqm3EAxH38mt4be-qo',
    'title': 'James Arthur - Back From The Edge',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_llBNVDBNncoPNlOvXcZSny32SLEFepdwQ',
    'title': "50 Cent - Get Rich Or Die Tryin'",
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mJLUX067d816Ur3BYLtUFRVE5AkK6PR8U',
    'title': 'Calvin Harris - 18 Months',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nAZAs495Fuv7ij62C3N50Ga7TAp60sq0w',
    'title': 'Linkin Park - Meteora',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kmtA2RV4sA_baCJwuaazeDtKmBM85j-yo',
    'title': 'Travis Scott - Utopia',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kPdPDkmggFWnDaTPs651iSKiz0gsp9R4s',
    'title': 'Macklemore & Ryan Lewis - The Heist',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kFAycOAlgpI743eKRTeGG82mwcwDoV4mc',
    'title': 'Calvin Harris - Motion',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kvi6xfWSkfUFjGtPHjvxuOcNsdnIlSUr8',
    'title': 'Ariana Grande - Sweetener',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_k-fR8UG9108cSGptPFWTQpRabw7Kyzc5c',
    'title': 'One Direction - Midnight Memories',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lmkszQnwSe59ADO4IPsiGylSTgz15P_yY',
    'title': 'Michael Jackson - Thriller',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_n13hmdsIozcCRyaY4cRDuuviphpfbzPrw',
    'title': "Guns N' Roses - Appetite For Destruction",
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_k0BfPls_ABfQsEcJfS4xxF81jXMHY3cjI',
    'title': 'The Neighbourhood - I Love You.',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lYlHqVN8M2AcghVbRCbX5rFHezLakV1Ds',
    'title': 'The Chainsmokers - Memories...Do Not Open',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nSf7ffoPgkzoAncS2eatbownOaZ2_X8i8',
    'title': 'David Guetta - Nothing But The Beat',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lQN_yR7RQie0jnpJ349k9psVApO4peUhc',
    'title': 'Dr. Dre - 2001',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_m4lOn8HJoLfTETxg2d6QouxcQd3nM4Gf0',
    'title': 'Coldplay - Parachutes',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nc7f_y7E_3cXhJmMkV8yq9CU2iqpnooug',
    'title': 'Sza - Ctrl',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mAGTQmYeosOR-Pp17OnnzkKHPeEbzSFOg',
    'title': 'Frank Ocean - Channel Orange',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_l6QK8fTSEZec6_jvhhDu1fmdM7a7ieYf4',
    'title': 'Halsey - Manic',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nyRZBNr6_NOMq4osjNSBbB7xpS2L_AH8w',
    'title': 'Eminem - The Marshall Mathers Lp',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nXEjdKtro80D3OQL2t0mnymJfQ6gTJGz4',
    'title': 'Shawn Mendes - Handwritten',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_m_LZ0LzQ487cBuuRehdrodyEkfoAUFiws',
    'title': "Luke Combs - This One'S For You",
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nkz7DeiXZnCzKNS4Di0gZv_58M-NEZAUo',
    'title': 'Kendrick Lamar & Various Artists - Black Panther',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mDdGJSv2u-3CO_Zb9Hm7rGGCo1e1L9_1s',
    'title': 'The Weeknd - Dawn Fm',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lYFD0sDFxZ8cr9ttczB7pH1zYc8r16kkg',
    'title': 'Jung Kook - Golden',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_ltXJSKxGWPdvV31htBGb_B9iQcSF7DH1w',
    'title': 'Paulo Londra - Homerun',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nBJRluT6ptlsBxn57aycyN-Fwh7k6_CAo',
    'title': 'David Guetta - 7',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_m_oiFQ5FK6PCTzskpi60YNQwxKZqkVD1M',
    'title': 'Eminem - Recovery',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_n64_SDF0otQBvjlDb_A5cSkkwT4R5ln00',
    'title': 'Cardi B - Invasion Of Privacy',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mla7F1QRwv6mBD0XEgHWm4eS-wmdNf97s',
    'title': 'Rihanna - Unapologetic',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kDChrO3UQuY4qQfOfgLj22p69pwGA4m0c',
    'title': 'Avicii - Stories',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_m1WZWUtrntyrrtCUSATYfs84K3ZnZl9P0',
    'title': 'Billie Eilish - Hit Me Hard And Soft',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mvRgYPh8u-KBTbU6mkGyrg5CBduos_LEY',
    'title': "Taylor Swift - 1989 (Taylor'S Version)",
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_m8NVy-6HVgRJ4e9gErhkY8LD0CRS1ORw8',
    'title': 'Khalid - Free Spirit',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mDm6sHCjqUcRpQaPVAGHHEY6uobsh0fVc',
    'title': 'Avicii - True',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mr6DjxLeVO2rPk8zAZx0F2_k5BaGuXlyQ',
    'title': "Sabrina Carpenter - Short N' Sweet",
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_k7FTSn7ydw3cNY9X5w2UJYVO7fLXPDTik',
    'title': 'Tame Impala - Currents',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lTUCPSiT_kZOCY1BlJ1t5T5nsxeG6v20s',
    'title': 'Tiesto - Drive',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lMaQ4IrRX4WFH9Kg2QBhJwMFFfnRx5wOE',
    'title': "Oasis - (What'S The Story) Morning Glory?",
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_k4igJBedQoNGRnRdPx2NP-ARZ64c03zHM',
    'title': 'Vance Joy - Dream Your Life Away',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lUwH9j_s3ZEeayUSm5o93gtQVz0If_kd8',
    'title': "Taylor Swift - Fearless (Taylor'S Version)",
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_l3qf_fJNreo3L6_ZPIaLOquqfTda--gZc',
    'title': 'Metallica - Metallica (Black Album)',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nN6ToczJSrgaKwaWT3jyvNgedNcs2D94Y',
    'title': 'Doja Cat - Hot Pink',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mRFuqe0IIrexXkU7JOxo4rOb0WLEcwuz8',
    'title': 'Kanye West - My Beautiful Dark Twisted Fantasy',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lbTwA-JDtWuF6vKJAtp98wZ512LtuqVoM',
    'title': 'Amy Winehouse - Back To Black',
    'image': null,
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nPamPQG3Yr23yUuXbMsvyHeIB6nnUjxak',
    'title': 'Lorde - Pure Heroine',
    'image': 'https://i.scdn.co/image/ab67616d0000b273187331e276c898d39764cc98',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lXRdq2EQXbT8pGSDQCSwKSXFt3LPVrWao',
    'title': 'Bryson Tiller - Trapsoul',
    'image': null,
    'isAlbum': true,
    'list': [],
  }
];
