name: ⭐ Feature Request
assignees:
  - gokadzev
description: Suggest a feature to improve the app
title: "[Feature] <title>"
labels: "type: enhancement"

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you're requesting.
      options:
        - label: I have searched the existing issues and confirmed that this feature is not already requested.
          required: true
        - label: I read the [FAQ section](https://github.com/gokadzev/Musify/discussions/340) and there's nothing mentioned about this feature.
          required: true

  - type: dropdown
    attributes:
      label: Category of the Feature
      description: Select the category to which your feature belongs.
      multiple: true
      options:
        - UI Improvements
        - Logical Improvements
        - More Efficiency
        - Performance Improvements
        - UX Improvements
        - Code Refactor
        - Unable to categorize

  - type: input
    attributes:
      label: Credits
      description: Who contributed to the idea of this feature?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Pain
      description: Describe the pain or problem you're experiencing that this feature would address.
      placeholder: e.g., I don't like that I have to do...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested Solution
      description: Describe your suggested solution for the feature.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Useful Resources/References
      description: Provide any useful resources or references that can help in implementing your suggested solution.
    validations:
      required: false
