name: youtube_music_explode_dart
description: Minimal YouTube Music innertube client for Musify artist pages.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  youtube_explode_dart:
    path: ../youtube_explode_dart
