// dart format width=80
// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'closed_caption_track_info.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

// dart format off
T _$identity<T>(T value) => value;

/// @nodoc
mixin _$ClosedCaptionTrackInfo {
  /// Manifest URL of the associated track.
  Uri get url;

  /// Language of the associated track.
  Language get language;

  /// Whether the associated track was automatically generated.
  bool get isAutoGenerated;

  /// Track format
  ClosedCaptionFormat get format;

  /// Create a copy of ClosedCaptionTrackInfo
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  @pragma('vm:prefer-inline')
  $ClosedCaptionTrackInfoCopyWith<ClosedCaptionTrackInfo> get copyWith =>
      _$ClosedCaptionTrackInfoCopyWithImpl<ClosedCaptionTrackInfo>(
          this as ClosedCaptionTrackInfo, _$identity);

  /// Serializes this ClosedCaptionTrackInfo to a JSON map.
  Map<String, dynamic> toJson();

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is ClosedCaptionTrackInfo &&
            (identical(other.url, url) || other.url == url) &&
            (identical(other.language, language) ||
                other.language == language) &&
            (identical(other.isAutoGenerated, isAutoGenerated) ||
                other.isAutoGenerated == isAutoGenerated) &&
            (identical(other.format, format) || other.format == format));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode =>
      Object.hash(runtimeType, url, language, isAutoGenerated, format);
}

/// @nodoc
abstract mixin class $ClosedCaptionTrackInfoCopyWith<$Res> {
  factory $ClosedCaptionTrackInfoCopyWith(ClosedCaptionTrackInfo value,
          $Res Function(ClosedCaptionTrackInfo) _then) =
      _$ClosedCaptionTrackInfoCopyWithImpl;
  @useResult
  $Res call(
      {Uri url,
      Language language,
      bool isAutoGenerated,
      ClosedCaptionFormat format});

  $LanguageCopyWith<$Res> get language;
}

/// @nodoc
class _$ClosedCaptionTrackInfoCopyWithImpl<$Res>
    implements $ClosedCaptionTrackInfoCopyWith<$Res> {
  _$ClosedCaptionTrackInfoCopyWithImpl(this._self, this._then);

  final ClosedCaptionTrackInfo _self;
  final $Res Function(ClosedCaptionTrackInfo) _then;

  /// Create a copy of ClosedCaptionTrackInfo
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? url = null,
    Object? language = null,
    Object? isAutoGenerated = null,
    Object? format = null,
  }) {
    return _then(_self.copyWith(
      url: null == url
          ? _self.url
          : url // ignore: cast_nullable_to_non_nullable
              as Uri,
      language: null == language
          ? _self.language
          : language // ignore: cast_nullable_to_non_nullable
              as Language,
      isAutoGenerated: null == isAutoGenerated
          ? _self.isAutoGenerated
          : isAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool,
      format: null == format
          ? _self.format
          : format // ignore: cast_nullable_to_non_nullable
              as ClosedCaptionFormat,
    ));
  }

  /// Create a copy of ClosedCaptionTrackInfo
  /// with the given fields replaced by the non-null parameter values.
  @override
  @pragma('vm:prefer-inline')
  $LanguageCopyWith<$Res> get language {
    return $LanguageCopyWith<$Res>(_self.language, (value) {
      return _then(_self.copyWith(language: value));
    });
  }
}

/// @nodoc
@JsonSerializable()
class _ClosedCaptionTrackInfo extends ClosedCaptionTrackInfo {
  const _ClosedCaptionTrackInfo(this.url, this.language,
      {this.isAutoGenerated = false, required this.format})
      : super._();
  factory _ClosedCaptionTrackInfo.fromJson(Map<String, dynamic> json) =>
      _$ClosedCaptionTrackInfoFromJson(json);

  /// Manifest URL of the associated track.
  @override
  final Uri url;

  /// Language of the associated track.
  @override
  final Language language;

  /// Whether the associated track was automatically generated.
  @override
  @JsonKey()
  final bool isAutoGenerated;

  /// Track format
  @override
  final ClosedCaptionFormat format;

  /// Create a copy of ClosedCaptionTrackInfo
  /// with the given fields replaced by the non-null parameter values.
  @override
  @JsonKey(includeFromJson: false, includeToJson: false)
  @pragma('vm:prefer-inline')
  _$ClosedCaptionTrackInfoCopyWith<_ClosedCaptionTrackInfo> get copyWith =>
      __$ClosedCaptionTrackInfoCopyWithImpl<_ClosedCaptionTrackInfo>(
          this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$ClosedCaptionTrackInfoToJson(
      this,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _ClosedCaptionTrackInfo &&
            (identical(other.url, url) || other.url == url) &&
            (identical(other.language, language) ||
                other.language == language) &&
            (identical(other.isAutoGenerated, isAutoGenerated) ||
                other.isAutoGenerated == isAutoGenerated) &&
            (identical(other.format, format) || other.format == format));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode =>
      Object.hash(runtimeType, url, language, isAutoGenerated, format);
}

/// @nodoc
abstract mixin class _$ClosedCaptionTrackInfoCopyWith<$Res>
    implements $ClosedCaptionTrackInfoCopyWith<$Res> {
  factory _$ClosedCaptionTrackInfoCopyWith(_ClosedCaptionTrackInfo value,
          $Res Function(_ClosedCaptionTrackInfo) _then) =
      __$ClosedCaptionTrackInfoCopyWithImpl;
  @override
  @useResult
  $Res call(
      {Uri url,
      Language language,
      bool isAutoGenerated,
      ClosedCaptionFormat format});

  @override
  $LanguageCopyWith<$Res> get language;
}

/// @nodoc
class __$ClosedCaptionTrackInfoCopyWithImpl<$Res>
    implements _$ClosedCaptionTrackInfoCopyWith<$Res> {
  __$ClosedCaptionTrackInfoCopyWithImpl(this._self, this._then);

  final _ClosedCaptionTrackInfo _self;
  final $Res Function(_ClosedCaptionTrackInfo) _then;

  /// Create a copy of ClosedCaptionTrackInfo
  /// with the given fields replaced by the non-null parameter values.
  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? url = null,
    Object? language = null,
    Object? isAutoGenerated = null,
    Object? format = null,
  }) {
    return _then(_ClosedCaptionTrackInfo(
      null == url
          ? _self.url
          : url // ignore: cast_nullable_to_non_nullable
              as Uri,
      null == language
          ? _self.language
          : language // ignore: cast_nullable_to_non_nullable
              as Language,
      isAutoGenerated: null == isAutoGenerated
          ? _self.isAutoGenerated
          : isAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool,
      format: null == format
          ? _self.format
          : format // ignore: cast_nullable_to_non_nullable
              as ClosedCaptionFormat,
    ));
  }

  /// Create a copy of ClosedCaptionTrackInfo
  /// with the given fields replaced by the non-null parameter values.
  @override
  @pragma('vm:prefer-inline')
  $LanguageCopyWith<$Res> get language {
    return $LanguageCopyWith<$Res>(_self.language, (value) {
      return _then(_self.copyWith(language: value));
    });
  }
}

// dart format on
