import 'package:flutter/material.dart';

final availableColors = <Color>[
  const Color(0xFF9ACD32),
  const Color(0xFF00FA9A),
  const Color(0xFFF08080),
  const Color(0xFF6495ED),
  const Color(0xFFFFAFCC),
  const Color(0xFFC8B6FF),
  const Color(0xFFFEDCBA),
  const Color(0xFFAABBCC),
  const Color(0xFFDDDDDD),
  const Color(0xFFFFC0CB),
  const Color(0xFFFFD700),
  const Color(0xFF008080),
  const Color(0xFF9932CC),
  const Color(0xFF00CED1),
  const Color(0xFFE9967A),
  const Color(0xFFFA8072),
  const Color(0xFFBDB76B),
  const Color(0xFFE6E6FA),
  Colors.blue,
  Colors.red,
  Colors.green,
  Colors.orange,
  Colors.purple,
  Colors.pink,
  Colors.teal,
  Colors.lime,
  Colors.indigo,
  Colors.cyan,
  Colors.brown,
  Colors.amber,
  Colors.deepOrange,
  Colors.deepPurple,
  Colors.grey,
];
